### ISSUE TITLE
Update new UI

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#104]
We had new design for Tomomaster, we should apply new design to the product

![cdx086lg](https://user-images.githubusercontent.com/546540/42334404-5e6d01ee-80a7-11e8-8cf2-924ac6fc9adc.png)

**Comment by hoangkianh** [comment]
- [ ] blocksigners/List.vue
- [ ] candidates/Apply.vue
- [ ] candidates/List.vue
- [ ] candidates/Resign.vue
- [ ] candidates/View.vue
- [ ] candidates/Withdraw.vue
- [ ] voters/Confirm.vue
- [ ] voters/Unvoting.vue
- [ ] voters/View.vue
- [ ] voters/Voting.vue
- [ ] Setting.vue
