### ISSUE TITLE
The server should not crash when it can't connect to the RPC target

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#117]
As for now, if the host filled in `WEB3_URI` is down, the server will just stop.
It should keep waiting for connection and maybe display a disclaimer for better UX
This is quite important as it's really problematic during deployments

**Comment by thanhson1085** [comment]
I already implemented checking the connection before start the service.

We should close this issue. For other 'connection on error' improvements, we can create a new issue.
