### ISSUE TITLE
Refactor Dockefile

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#135]
And I have some other comments:
Remove truffle
```
npm install -g pm2 truffle
```

Use:
```
npm install --production
```

**Comment by thanhson1085** [comment]
`COPY . .` should not be there
It should be:
```
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .
```
See https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by thanhson1085** [comment]
And the dockerfile should support users who have no nodejs knowledge. So they can run the application, just need change config file and run docker.

**Comment by etienne-napoleone** [comment]
Concerning the configuration, we should not use any configuration file, it should be passed through environnent variable of the container.
Please give me a list of the needed ones and I will add them

**Comment by thanhson1085** [comment]
In `config/default.json`. The lines:
```
  "truffle": {
    "mnemonic": "",
    "minCandidateCap": "50000000000000000000000",
    "maxValidatorNumber": 99,
    "candidateWithdrawDelay": 100,
    "voterWithdrawDelay": 100,
    "epochNumber": 990,
    "randomNumber": 99
  }
```

That is for smart contract deployment, so you don't need to pass through it to environment variables

**Comment by etienne-napoleone** [comment]
I created branch [tomochain/tomomaster(feature/refactordockerfile)](https://github.com/tomochain/tomomaster/tree/feature/refactordockerfile) to work on it.
@thanhson1085 can you check why I get `RPC connection lost - shut down service
` when running it? ( https://github.com/tomochain/infrastructure/blob/feature/refactortomomaster/deploy/tomomaster.yml )

**Comment by thanhson1085** [comment]
It means that tomomaster is not able to connect tomochain node. Make sure that the node is still live

**Comment by etienne-napoleone** [comment]
Yes for sure!
The node is alive and I can telnet to the port 8545 without problem.
I think it's because it's not taking the ENV variables in consideration. Can you take a look at my changes in:
https://github.com/tomochain/tomomaster/blob/feature/refactordockerfile/Dockerfile
and
https://github.com/tomochain/tomomaster/blob/feature/refactordockerfile/config/local.json
?
From what I read it should take the environment variable into account
