### ISSUE TITLE
Display "estimated time" for withdraw

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#183]
We should have time estimation for withdrawing TOMO after unvote or resign.

We can calculate time estimation from block number.
![wdraw](https://user-images.githubusercontent.com/546540/44895761-f9b85a00-ad1f-11e8-989c-f2756acae679.JPG)

**Comment by pqv199x** [comment]
Implementation pull request:
https://github.com/tomochain/tomomaster/pull/184
