### ISSUE TITLE
Should have way to show real reward value

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#188]
In the table, it is just should a fixed value

<img width="237" alt="screen shot 2018-09-04 at 22 45 56" src="https://user-images.githubusercontent.com/546540/45042394-cade1300-b094-11e8-94d8-5edd2da50929.png">

**Comment by thanhson1085** [comment]
should show 6-8 decimals

**Comment by khaihkd** [comment]
I think 4-5 is enough
