### ISSUE TITLE
How to undo my unvoting?

### ISSUE THREAD

**Issue by anhntv2012** [tomochain/tomomaster#209]
I unvoted Masternode Sun by 1.2 TOMO. Now I want to undo that action. How could I?

(1) I tried to vote for Sun by 10 TOMO. My votes for Sun increased by 10 TOMO and 1.2 TOMO is still locked.
Does it make more sense if  it goes that my votes for Sun increases by 8.8 TOMO and nothing is locked?

(2) I just want to undo my 1.2 TOMO unvoting. How should I do?

**Comment by thanhson1085** [comment]
You can not undo the unvote with current version of Voting Smart Contract.
This is a good suggestion.

I will think a way to implement it. But it is not easy to upgrade the smart contract, it will be take a lot of trade off, e.g, reset whole data of testnet

**Comment by anhntv2012** [comment]
Pls make sure that we can unvote with the voting smart contract in the mainnet. Thank you.
