### ISSUE TITLE
Graphs are too complicated

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#249]
[Reference](https://master.testnet.tomochain.com/candidate/0x90baf4c0d505c838ba23aa9c6054843ff8816d53)
### General
- Legends are over complicated. Should be like `CPU usage (%)` not `dkkris_17f841_cpu_user`
- The `group_by time()` should be higher to smooth the graph and take advantage of the nice UI we have. We would not even lose much precision. The tick rate being quite high (5s iirc).
### CPU graph
The CPU graph is overly complicated. It should not be like this when the goal is to provide simple informations to help people chose a masternode.
For now, the CPU graph has two metrics. the cpu idle cycles and the cpu user cycles. It requires some knowledge to know what it means and it doesn't look straightforward.
CPU should be `CPU_IDLE * -1 + 100` like [here](https://grafana.testnet.tomochain.com/d/Q2vSHapmz/alerting-manager?refresh=10s&panelId=2&fullscreen&orgId=1).

**Comment by etienne-napoleone** [comment]
Today someone make the remark "Wow all CPUs are at 100%!" when they are actually all around 1/2%

**Comment by thanhson1085** [comment]
the chart was removed
