### ISSUE TITLE
Tables are hard to use

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#250]
### Weird and confusing alignment
Right aligned columns have a problem with there headers. It looks bad and really weird/confusing.
<img width="1156" alt="screen shot 2018-10-25 at 10 31 49" src="https://user-images.githubusercontent.com/26155267/47474500-6ee86d00-d841-11e8-894d-bea10f67587f.png">
Why is it even right aligned here? Could be just left aligned like all the rest.
<img width="1179" alt="screen shot 2018-10-25 at 10 34 31" src="https://user-images.githubusercontent.com/26155267/47474547-a5be8300-d841-11e8-9c84-e7e080c29c66.png">
Looks really out of place here
<img width="1159" alt="screen shot 2018-10-25 at 10 37 42" src="https://user-images.githubusercontent.com/26155267/47474633-08b01a00-d842-11e8-9f8c-a20e0d8aa25d.png">
Same here
<img width="1169" alt="screen shot 2018-10-25 at 10 38 34" src="https://user-images.githubusercontent.com/26155267/47474700-604e8580-d842-11e8-87fd-2d67e4b21875.png">
Why not just align all to the left? Also, why is the "view on TomoScan" compressed here in the middle? It could have it's own column at the end of the row
### Candidates list
Some weird spacing is going on between the columns
<img width="580" alt="screen shot 2018-10-25 at 10 36 15" src="https://user-images.githubusercontent.com/26155267/47474614-f504b380-d841-11e8-8c73-8a298b6723d7.png">

### Voters
Cannot order by time (ID). Which means the ID column will always be messy.
<img width="1163" alt="screen shot 2018-10-25 at 10 28 40" src="https://user-images.githubusercontent.com/26155267/47474351-c2a68680-d840-11e8-856e-c2b3ef282f6f.png">

### Signs
The ID column doesn't make sense/is useless as it's only numbering items from 1 to 10 in the current pagination.
<img width="1179" alt="screen shot 2018-10-25 at 10 19 31" src="https://user-images.githubusercontent.com/26155267/47474099-b0781880-d83f-11e8-9d83-f5008746bc2a.png">

### Transactions
Cannot order by id or age. Which feels pretty clunky when you just voted and want to see your vote
<img width="1158" alt="screen shot 2018-10-25 at 10 24 51" src="https://user-images.githubusercontent.com/26155267/47474267-5f1c5900-d840-11e8-9929-827cbcc44d13.png">

**Comment by pqv199x** [comment]
Fixing pull request:
https://github.com/tomochain/tomomaster/pull/251
