### ISSUE TITLE
When user does not Login

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#272]
"not Login" means:
- not connect to a correct network (exists TomoValidator in that network)
- not Login to user's wallet

Expectation:
- Button "Become a candate" => "Login" (go to /setting page), hide 3(.) button
- Disable Vote button (gray color)

<img width="1324" alt="screen shot 2018-10-31 at 21 29 52" src="https://user-images.githubusercontent.com/546540/47795316-edb73b80-dd54-11e8-9f39-d2b03b38f896.png">

<img width="457" alt="screen shot 2018-10-31 at 21 34 07" src="https://user-images.githubusercontent.com/546540/47795298-e6902d80-dd54-11e8-9379-06bc24a2ec11.png">

**Comment by pqv199x** [comment]
Implementation pull request:
https://github.com/tomochain/tomomaster/pull/283
