### ISSUE TITLE
Search function/Help button

### ISSUE THREAD

**Issue by anhntv2012** [tomochain/tomomaster#282]
1. Search does not work if the input is not an address, which is not user friendly (and there's no warning about this on the screen, which actually made me think that it's a bug). Can we search by the name of the candidate/masternode?
2. Can we have a "Help" or "Get familiar with TomoMaster" button which is linked to https://docs.tomochain.com/tomomaster/features/ . People really can get lost when they first navigate TomoMaster.

**Comment by thanhson1085** [comment]
I think we can implement No.1 without supporting from Designer
@pqv199x
