### ISSUE TITLE
Filters don't work with sticky sessions

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#297]
When load balancing RPC endpoints with cookie sticky session, web3 httpProvider seems to not take it into consideration.

See initial issue on web3 repo https://github.com/ethereum/web3.js/issues/1665 and fixing PR https://github.com/ethereum/web3.js/pull/1722

We should
- [ ] test replacing by websocket provider and check if the same problem happens (as we use truffle, we don't directly manage web3)
- [ ] test if this cause problem for dapp developers who will use our RPC endoint

**Comment by thanhson1085** [comment]
related to #298 @khaihkd

**Comment by etienne-napoleone** [comment]
>test if this cause problem for dapp developers who will use our RPC endoint
What about this?

**Comment by thanhson1085** [comment]
They will meet the issue with 'watch events' from chain. The support should be same as https://github.com/INFURA/infura/issues/73

**Comment by etienne-napoleone** [comment]
Ok, so not all filters?

**Comment by thanhson1085** [comment]
"watch events" will call 'filter' function from node via RPC endpoint. Our RPC endpoint does not support it, same as Infura.

They should use "watch events" with Websocket endpoint, or they should run their own fullnode to own their RPC endpoint

**Comment by etienne-napoleone** [comment]
ok got it! thanks
