### ISSUE TITLE
Transaction age is related to date of crawl, not date of transaction

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#309]
![image](https://user-images.githubusercontent.com/26155267/48597945-0a798300-e993-11e8-8c70-76aa9790179a.png)

Those transactions were made one or two days ago.

**Comment by etienne-napoleone** [comment]
ah false alarm, problem with RPC

**Comment by thanhson1085** [comment]
that is an issue, fixed https://github.com/tomochain/tomomaster/pull/311

**Comment by etienne-napoleone** [comment]
ah oups! Ok good
