### ISSUE TITLE
Login with metamask lost on page refresh

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#310]
When soft refreshing the page (ctrl+r), I lose my metamask login.

**Comment by thanhson1085** [comment]
currently, metamask is not a default network provider for tomomaster. We will recommend them to use TomoWallet https://github.com/tomochain/tomomaster/pull/308

**Comment by etienne-napoleone** [comment]
Yes but in case the person use MetaMask, I don't think being disconnected on page refresh terrible regarding UX.

**Comment by thanhson1085** [comment]
yep, should be fixed
