### ISSUE TITLE
Enable requests logging

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#363]
Easier for debugging

**Comment by thanhson1085** [comment]
Use this https://github.com/expressjs/morgan, 
Log level DEBUG @pqv199x

**Comment by etienne-napoleone** [comment]
Thinking twice, maybe it's overkill. I'll close it for now. If you think we should still implement it, feel free to reopen it.

**Comment by thanhson1085** [comment]
We need to monitor the paths, but we do not use nginx. So the app should logs the paths
