### ISSUE TITLE
Address formating

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#364]
What do you guys think about displaying hashes in a shorter way when it's possible?
For ex:
![screenshot from 2018-12-08 11-18-59](https://user-images.githubusercontent.com/26155267/49681837-3643e080-fadb-11e8-8065-162cbd7894ac.png)

**Comment by pqv199x** [comment]
Done: https://github.com/tomochain/tomomaster/commit/f823d2b96bb6b7615f6d3e49fec4125ce609696e

![image](https://user-images.githubusercontent.com/24842503/57070933-1d92cc00-6d03-11e9-94ab-ff8a71ad26ed.png)
