### ISSUE TITLE
Rethink withdraw timer

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#428]
Currently, the withdraw estimation is really misleading and frustrating for users.
Can get up to +30% than the displayed time as not all blocks are 2s.

Must think about a better way to present it.

**Comment by thanhson1085** [comment]
Show "current block number" instead of "estimated" time @pqv199x

**Comment by pqv199x** [comment]
Changing `Estimated Time` to `Current Block Number` could reduce confusion for user, but it will make some duplications
![image](https://user-images.githubusercontent.com/24842503/50623304-dcea9800-0f46-11e9-9e90-561761094e6d.png)

**Comment by pqv199x** [comment]
Should we remove `Estimates Time`?
![image](https://user-images.githubusercontent.com/24842503/50623481-f55bb200-0f48-11e9-9f93-21fcc53c4f69.png)

**Comment by thanhson1085** [comment]
Ok, also remove Current Block Number
