### ISSUE TITLE
Tx Fee Estimate

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#434]
We display Tx Fee in vote/unvote/apply screen. But just hard-coded.

It should be hard estimated by GasLimit * GasPrice

**Comment by pqv199x** [comment]
Do we have a specific amount for gas and gasPrice?
I see that amount of gas is not same some function, Ex: vote and unvote is 1000000 while other functions are 2000000. For apis(vote, unvote, apply, resign) that are marked `for automation test only`, the amount of gas is 2000000

I'm planning to move gas and gasPrice to the configuration file(blockchain.gas and blockchain.gasPrice)

**Comment by thanhson1085** [comment]
gas is depended on the function in Smart Contract.
We can call gasEstimated, but our chain, the fee is very low. So we can config gas is 2000000 for all function
