### ISSUE TITLE
Add "withdraw"/"resign" tx to voter txs table

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#445]
Crawler should catch "withdraw" tx and store to db.
In txs table, display "withdraw" txs

**Comment by pqv199x** [comment]
For resign txes, I can change the query from 
```
{
            smartContractAddress:
            voter
}
```
to 
```
{
            $or: [
                {
                    smartContractAddress
                    voter
                },
                {
                    smartContractAddress
                    owner
                }
            ]
        }
```

![image](https://user-images.githubusercontent.com/24842503/51171242-f1357a00-18e2-11e9-82a4-b4ef6336cd5d.png)

**Comment by pqv199x** [comment]
withdraw txes are stored in withdraw table, but each record does not have event(ex: vote, unvote, resign...). In addition, it is hard to combine 2 tables transaction and withdraw

**Comment by thanhson1085** [comment]
we should modify crawler add resign/withdraw tx to browser
