### ISSUE TITLE
Store "slashed" history

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#446]
Crawler should store "slashed" history, then we can show the history in the site

**Comment by thanhson1085** [comment]
It should be crawl all slashed data from block 1

**Comment by thanhson1085** [comment]
We will need to display "slashed" number/48 epochs in candidate detail page

**Comment by pqv199x** [comment]
New:
slashed times in a week
combile slashed time with reward table

**Comment by pqv199x** [comment]
new pull request: https://github.com/tomochain/tomomaster/pull/501
