### ISSUE TITLE
Search bar UX problem and add option to search by the name of candidates

### ISSUE THREAD

**Issue by miketomochain** [tomochain/tomomaster#452]
Some search bar UX problems:

**1. The button "Search" is unnecessary**

<img width="603" alt="search bar ui" src="https://user-images.githubusercontent.com/46370751/50883955-2b52d780-141c-11e9-99a6-476ec24d1059.png">

According to the search habit of the majority of users on the most popular sites/applications such as Facebook, Instagram, or even Github, they will type the keywords right into the search bar and press Enter to carry out the action. Hence the button "Search" would create one more unnecessary step, and we can save the space if removing it. 
It could be look like this:
<img width="591" alt="search bar" src="https://user-images.githubusercontent.com/46370751/50884086-77058100-141c-11e9-9303-95ac2f1019c5.png">

**2. Add suggestions section when typing keywords into search bar**

Adding suggestions when typing keywords would help search experiences become more interactive, faster and more convenient. 

**3. Adding option to search by the name of candidates:**

In some case, for quick search purpose, typing keywords by the name would be a more user-friendly option than typing address

**Comment by hoangkianh** [comment]
@thanhnguyennguyen let me solve this problem.
