### ISSUE TITLE
It takes 2 mobile devices to log into TomoMaster on mobile version 

### ISSUE THREAD

**Issue by miketomochain** [tomochain/tomomaster#458]
On TomoMaster mobile version, we have to need 2 mobile devices to log in. One for TomoMaster Screen, one for the QR code scanning , it's quite inconvenient

**Comment by Logle** [comment]
This should be reported to mobile wallet team @miketomochain

**Comment by pqv199x** [comment]
You dont need 2 devices. With this https://github.com/tomochain/tomomaster/pull/437. Tomomaster mobile version now has a button `Open in App` which will activate your device to login via Tomowallet app
