### ISSUE TITLE
Add notification section and create a menu section below the profile icon

### ISSUE THREAD

**Issue by miketomochain** [tomochain/tomomaster#476]
**1. Add notification section (as the image below)**
Added a notification section to send notifications to users, for example, when masternode they voted is slashed/resigned,  there is a new updated version or anything change

**2. Create a menu section below the profile icon for users (as the image below)** 
Create a menu section could help users understand that they have successfully logged in, more easily to manage their personal wallet information and have the option to log out.

<img width="642" alt="fixed" src="https://user-images.githubusercontent.com/46370751/51456960-1feb9e80-1d82-11e9-9872-a7999226a510.png">

**Comment by pqv199x** [comment]
pull request for the second option:
https://github.com/tomochain/tomomaster/pull/524
