### ISSUE TITLE
Keep the same masternode candidate page you are viewing after visiting any masternode candidate detail and back

### ISSUE THREAD

**Issue by miketomochain** [tomochain/tomomaster#481]
For example, I'm staying on page 2 of masternode candidates list, I click to 1 masternode candidate to see more detail, but when I get back, instead of staying on page 2, I’m back to page 1. It should be back to the current page to continue exploring, rather than being back to the beginning

**Comment by pqv199x** [comment]
Duplicate, solved issue: https://github.com/tomochain/tomomaster/issues/424

**Comment by pqv199x** [comment]
https://github.com/tomochain/tomomaster/commit/4b57569558800d975b6ad46a25239fd6852fa3c6
