### ISSUE TITLE
Total "Candidates" and Resigned Masternode Candidates

### ISSUE THREAD

**Issue by MartQC1** [tomochain/tomomaster#488]
On the main page, and following https://github.com/tomochain/tomomaster/issues/429, the number of Candidates excludes the Resigned Masternodes.

It is however somewhat confusing for a user with little experience to understand why the title of the table "Candidates" indicates for example 144 candidates and then he can browse the table showing all candidates and there is like 160 lines (because 16 candidates have resigned).

Would it be appropriate to list the Resigned masternode in a separate table than the Candidates?

Else, the list of masternodes could be numbered in a way that a user with little experience would understand where the number 144 comes from (and do not think there is a problem with the counter). Example:

![rank masternode](https://user-images.githubusercontent.com/46986059/51655066-f6d93280-1f68-11e9-8ff5-a34a51391963.png)

In any case, numbering the candidates could be useful to rapidly see where the candidates stands in the overall network.

**Comment by thanhson1085** [comment]
Duplicated, https://github.com/tomochain/tomomaster/issues/479
