### ISSUE TITLE
Proposition of statistics to add on a MN page

### ISSUE THREAD

**Issue by MartQC1** [tomochain/tomomaster#489]
I understand that the goal of Tomomaster is to provide useful information to help a potential staker make a good staking decision.

On a masternode page, this one:

![stats page mn](https://user-images.githubusercontent.com/46986059/51655235-bb8b3380-1f69-11e9-84a1-e144be946b90.png)

It could be useful to have the following statistics (if possible):

**Candidate Experience:** this would be the total of occurence where a candidate (_ie_ a given coinbase address) has received an Infrastructure Reward. This would be useful for a potential staker to know if it is voting for a node having experience, and thus potentially for a node operator intending to be "in the game" on the long term, OR if it is voting for a node that has been online for a few days only and maybe he is voting for an operator that could Resigned in the near future if he decides to abandon the project of running a node.

**Slashed Occurence in the last XXX epochs:** this would be the total of times a candidate went from Masternode to Slashed in the last XXX epochs. I think it should only show a certain period in the past, because we do not want to penalize, for example, operators that had difficulties in the past and then upgraded their specs and that are now working perfectly. Maybe it could show the stats for the last 30 days (based on a block time of 2 seconds).

**Average Slashed Duration:** this could show how much epochs in average for a candidate to go from Slashed to Masternode for each of the occurence mentioned in the precedent stats. This would indicate to a potential voter if the node operator is responsive when a problem happens. For example, I would prefer to vote for someone that is slashed 4 times in the last XXX epochs for only 2 epochs each time instead of voting for someone slashed 1 time in the same period but that remained slashed for 60 epochs.

**Comment by pqv199x** [comment]
slashing history: https://github.com/tomochain/tomomaster/pull/517
