### ISSUE TITLE
 Masternode Rewards on stats page should not take the stake into account

### ISSUE THREAD

**Issue by MartQC1** [tomochain/tomomaster#490]
Stats page:

![stats page mn](https://user-images.githubusercontent.com/46986059/51655858-7e747080-1f6c-11e9-9a4b-11a570465180.png)

Currently, on the stats page, we indicate the "Reward" earned by a masternode for each epoch.

At the moment, the "Reward" amount takes into account the Infrastructure Reward AND the Staking Reward.

It can give the false impression to a user with little experience that a node performs better than the other if the "Reward" is higher. This is false because if 2 nodes sign the same number of blocks, one could get a bigger "Reward" only because the node operator staked more Tomo in it than the other and the node of the first have a smaller Capacity. 

If we want to give information to the voter to help him make good decision, the only relevant Reward is the Infrastructure Reward, which is linked to the number of block signed. **The staking reward is not in any way linked to the masternode performance.** It is a reward that a node operator would get if voting for himself or for any other masternode.

I also think that at the protocol level, we should separate staking rewards and infrastructure rewards as it was the case at the launch of mainnet so we could easily differentiate them in Tomoscan. This will be useful for tax purposes and also if a group of user want to create a joint venture for running a node (they could decide to split the Infracstructure Reward equally, while they would split the staking reward in proportion of their stake since they would earn this reward any way if they were not running a masternode... at the moment it is very hard to know what is what).

**Comment by nyeates** [comment]
I second and third this. We were talking about it amongst a group of Masternode owners. It’s very confusing to both voters and owners. Voter could perceive you as receiving less rewards (less powerful server). MN operators think other servers are getting unfair reward compensation.

**Comment by thanhson1085** [comment]
done in v1.3.0
