### ISSUE TITLE
node shows 'proposed' when inside top 150 due to higher voted nodes being slashed

### ISSUE THREAD

**Issue by gussulliman** [tomochain/tomomaster#505]
When nodes in top 150 are slashed, 'proposed' nodes remain 'proposed' in the tomomaster ui, when they should be identified as Masternodes during this period. 

This would help increase incentive towards masternodes that are up and operating and away from nodes that are slashed.

**Comment by gussulliman** [comment]
It also appears these are not getting rewards (tomoscan and tomomaster for when one of the 150 is slashed.

**Comment by thanhson1085** [comment]
the suggestion relates to TomoChain consensus, not for TomoMaster.
