### ISSUE TITLE
Performance Of Nodes

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#518]
I propose "Performance" index to define a good node.

It will be easy to a newbie to determine a good node, just need to look at only one index - Performance 
Performance will be an index that is calculated from Slashed History, Latest Signed Block and Status 

We have:
Current block: **C**
Latest Signed Block: **L**
Slashed epochs in the latest 100 epochs: **S**, and **P** = 100 - S
Performance: **X** %

Case 1: status = MASTERNODE:
If C  - L  >  900 => X = 0 %
If (C - L) <= 900 and (C -L) < 450 => X = P  - 25 (X = 0 if P - 50 < 0)
If (C - L) >= 450 => X = P 

Case 2: status = SLASHED, RESIGNED, PROPOSED => X = 0

Colors of X:
if X >= 90 => GREEN
if X < 90 and X  >= 50 => YELLOW
if X < 50 => RED

**Comment by Logle** [comment]
Firstly, latest 100 epoch is only only a bit more than 2 days. Historical performance should be based on much longer time frame such as least 2000 epoch ( ~ 45 days). This point has been raised by multiple users for example: "Is there a way to check historic performance of master nodes before you cast your vote? I only see the current status, but don't know how reliable the node has been in the past."

**Comment by thanhson1085** [comment]
This issue just propose an index that users can determine a good node or not in the look.
For "Performance History" should be discuss in another issue.

**Comment by Logle** [comment]
From user's perspective: a 'good' node is a historically reliable node that they can vote on. Why is that so difficult to understand?

**Comment by thanhson1085** [comment]
My point of view, a 'good' node is:
- current status is OK (no slashed, latest signed block is OK)
- a historically reliable node

I propose this issue for the first point.

**Comment by Logle** [comment]
Why do you use 'performance index' to refer to OK current status? I am concerned for user experiences in using product, especially in new features. New feature should be something that easy to understand and explain to all users. Feature naming should not be confusing.

**Comment by thanhson1085** [comment]
Just propose for the discussion. Do you have any suggestion the name?

**Comment by Logle** [comment]
OK current status/ current status index/ current status are okay. There should be a written product change log when new version is published which is sent to community and support team. That helps with community supports @miketomochain should take note.

**Comment by thanhson1085** [comment]
Currently, we already had "status" (MASTERNODE, SLASHED, PROPOSED). Add "current status" will be more confused.

**Comment by Logle** [comment]
Then you should not add this new thing. This issue "current status is OK (no slashed, latest signed block is OK)" is not adding values to end-user experience because we already have a very close indicator "status" (MASTERNODE, SLASHED, PROPOSED).

**Comment by thanhson1085** [comment]
Ok, will close this issue.
But "slashed" "latest signed block" is not friendly with newbies

**Comment by Logle** [comment]
I read the issue and suppose that a new indicator is being added. It isn't clear that old terms and statistics will be replaced or kept in the issue. "slashed" "latest signed block" aren't too bad with crypto users though.

**Comment by thanhson1085** [comment]
the old terms will be kept in the issue.
Actually, the priority of this issue is not high, we can re-open it for TomoMaster 2.0.
