### ISSUE TITLE
Bug masternode status

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#540]
A node is proposed status but show 'slashed' node
![capture](https://user-images.githubusercontent.com/546540/53630896-c78ea300-3c43-11e9-8caa-f7aa34eab950.PNG)

The slashed node above is a node with lowest capacity

**Comment by pqv199x** [comment]
The current crawler is updating Signers, Candidate(status), Penalty, Status tables every 5 blocks. This may 
cause incorrect information displaying.

**Comment by thanhson1085** [comment]
move issue to tomochain https://github.com/tomochain/tomochain/pull/471
