### ISSUE TITLE
All MN Transactions List

### ISSUE THREAD

**Issue by tcKONG** [tomochain/tomomaster#579]
hi, 

could there be a running MN transactions list? 
either through scan or master that lists all MN votes & unvotes without visiting each MN or voter separately? 
hopefully each MN is listed by name & not just address & includes capacity after transaction
![mn transaction list](https://user-images.githubusercontent.com/46321061/55030160-1f6dbf00-4fe2-11e9-8b47-763bfd77ea3d.PNG) 
https://imgur.com/AAthTpo

**Comment by pqv199x** [comment]
Thank you for creating the issue and sorry for the late reply.
This is my answer:
A masternode transaction list will have huge data, vote unvote, propose, resign txes of > 150 MN. As a result, it will not easy to focus on a MN that a user is looking for.

**Comment by thanhson1085** [comment]
Add "masternode name" column is easy. But "current capacity" requires more works. But this a good suggestion for masternode owner

**Comment by tcKONG** [comment]
Thanks, small steps are better than none!
