### ISSUE TITLE
Block get stuck !!!!

### ISSUE THREAD

**Issue by richardwing121** [tomochain/tomomaster#658]
Hello For testing I created 15 masternode with posv and proposed the masternode on the tomo master app but after certain time I lost my coin base address and 11 nodes are down and get slashed and all the nodes are stuck I can not see any block syncing any data on master node app And block also got stuck in the middle
How can I fix it? It would be great if you can provide any solution

**Comment by thanhson1085** [comment]
closed, refer to the issue in TomoChain Repo
