### ISSUE TITLE
Est. daily reward is incorrect

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomomaster#662]
![Capture](https://user-images.githubusercontent.com/546540/59096052-3155d180-8944-11e9-8d96-5594fba8eba6.PNG)

It should be around 1.8 - 2 TOMO

**Comment by pqv199x** [comment]
An API from tomoscan(get the total signature number) returns wrong data(double value). This cause the estimated value is wrong

**Comment by thanhson1085** [comment]
Got it, thanks
