### ISSUE TITLE
Coinbase address not displaying balance

### ISSUE THREAD

**Issue by tcKONG** [tomochain/tomomaster#695]
Coinbase address not displaying balance
![coinbase](https://user-images.githubusercontent.com/46321061/63384038-0c320600-c36c-11e9-8509-bc7e779b90f8.PNG)

**Comment by pqv199x** [comment]
You have to login in order to see the balance

**Comment by tcKONG** [comment]
Thanks, I can see balance in scan without login. it used to be displayed in tomomaster, will the field be removed?

**Comment by thanhson1085** [comment]
Yep, I think we should remove the balance field
